services:
    AppBundle\Controller\:
        resource: '../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    # decorate the oro_catalog.layout.data_provider.featured_categories service
    featured_category_provider_decorator:
        class: AppBundle\Layout\DataProvider\FeaturedCategoriesProvider
        decorates: oro_catalog.layout.data_provider.featured_categories
        arguments:
            - '@featured_category_provider_decorator.inner'

    event_listener.increase_rounded_number:
        class: AppBundle\EventListener\IncreaseRoundedNumberListener:
        tags:
            - { name: kernel.event_listener, event: app.round }
