services:
    # decorate the oro_catalog.layout.data_provider.featured_categories service
    oro_catalog.layout.data_provider.featured_categories:
        class: AppBundle\Layout\DataProvider\FeaturedCategoriesProvider

    event_listener.increase_rounded_number:
        class: AppBundle\EventListener\IncreaseRoundedNumberListener
        tags:
            - { name: kernel.event_listener, event: app.round }
